build: false

environment:
  matrix:
    - PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda
    - PYTHON_VERSION: 3.5
      MINICONDA: C:\Miniconda35
    - PYTHON_VERSION: 3.6
      MINICONDA: C:\Miniconda36

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - "conda env create -q -n test-environment python=%PYTHON_VERSION% -f environment.yml"
  - activate test-environment
  - conda install nose coverage pip
  - pip install git+https://github.com/lkilcher/pyDictH5.git

test_script:
  - nosetests
